### ISSUE TITLE
Generate doesn't works 

### ISSUE THREAD

**Issue by al3dv2** [Shaamallow/texture-diffusion#10] opened 2024-11-15 21:51 UTC
Hi I have a bug with texture-diffusion when I click on Generate I've a error message : 
![argggdc](https://github.com/user-attachments/assets/4b7a0f38-d64d-4090-84f6-5e94e045425a)
Also the interface become very laggy when I click on diffusion tab and I have a very powerful computer with 24go of vram etc

**Comment by Shaamallow** [comment] 2024-11-15 23:49
Hello, I'm struggling to reproduce your bug. Can you make a small video to help me understand what you are doing exactly so that I can locate the bug ? Thank you very much. 

Here is an example of me using the add-on. Try to reproduce the same steps so that I can help :pray: 

https://github.com/user-attachments/assets/edc076d5-13d4-4475-b045-485869b74019

Also, I've realized that you are using blender 4.3, I haven't tested it yet. I don't know if it breaks compatibility. I'm going to try it tomorrow to check. In the meantime, you can also try with blender 4.2 and tell me if you are still running into the error. 

I see that you don't have the "modifier" slot in your properties view, I am using the projection modifier to modifier the UV mesh of the selected object (see screenshot attached) to project it from the Camera. I'll check starting from this as soon as you can send me a video of the failed attempt. 

![image](https://github.com/user-attachments/assets/1cdfda69-02ca-4838-a206-d6d060f58379)

I noticed that Blender lags a bit for the 1st render on my laptop as I don't have a dedicated GPU but can run quite smoothly with one (as you can see on the video). I'll try to tackle that issue as well if possible

- Can you check if you have a Depth Image that is generated properly ?
![image](https://github.com/user-attachments/assets/9b4650c5-9d81-46ed-867f-914a2b1e5e7c)
- Can you check if your model has a new UV Map ?
![image](https://github.com/user-attachments/assets/e63e5bc7-e039-4e02-912d-acdb8d6e6145)

**Comment by Shaamallow** [comment] 2024-11-15 23:55
Also, you might run into another issue if the model you have chosen is not an 'SDXL' type of models (if it's a flux one, please add 'flux' to its name so that the add-on picks the right workflow, check out the doc [here](https://github.com/Shaamallow/texture-diffusion?tab=readme-ov-file#model-compatibilities) there is some [logic](https://github.com/Shaamallow/texture-diffusion/blob/main/src/operators/generation_operators.py#L187C1-L187C47) to pick one of the 2 [workflows](https://github.com/Shaamallow/texture-diffusion/tree/main/workflows))

**Comment by al3dv2** [comment] 2024-11-16 05:56
I made a video 

https://github.com/user-attachments/assets/53e91913-3eb2-4d3d-a654-c9b571c28cb0

In the comfyui workflow I need to put some picture in the upload images ?

**Comment by Shaamallow** [comment] 2024-11-16 10:30
Thank you very much for making the video, it's in fact **very slow** I'm also quite surprised as even on my potato laptop PC it's faster (the comfyUI workflow is not running on the laptop though). 
You don't need to load the workflow to upload images on the comfy interface, though. It's going to do that automatically, you can close the browser tab.

But, turns out you are now getting another error ! It's an error about the filepath now. What kind of filepath are you using in the `Properties > Output > Output > Path` tab ? I would like to check that, as the error message is telling that it struggles to find the following path : `C:\\Users\Shadow\Desktop\texturingAI\dfd\depth_5.png`
Try to check around that directory if the `depth_5.png` image has been generated. It would help to debug as well

**Comment by al3dv2** [comment] 2024-11-16 12:17
I changed the path ouput by C:\texturingAI\ and now it's works ! but it still very slow through
![workss](https://github.com/user-attachments/assets/e7c9747b-7295-4c25-b40c-93b3d075db4e)

**Comment by Shaamallow** [comment] 2024-11-16 12:37
Great news, probably blender version that was blocking at first. I'll give it a check asap. Still wondering why it's this slow. Generation time is dependent on your computing power and I can't optimize that but blender shouldn't lag after the depth is rendered (meaning only the first few seconds because that is using your GPU/CPU if not available). I'll give it a check as well but happy to hear that it's working now.

I'm closing the issue, happy texturing.

**Closed** 2024-11-16 12:37 UTC
